Add a --with-arch-flags configuration option to specify target architectures.
They allow the user to specify flags to indicate the target
architecture(s) (yes, possibly plural - think, for example, Mac OS X)
for which we're building.  Those might need to be used not only when
compiling, but also when linking and when building a shared library.

This is not for general cross-compiling, it's for use on platforms where
versions of the native OS support more than one instruction set and
where you want to build for the OS on which you're running but not for
the default build architecture on the machine on which you're running.

This may currently be less useful for tcpdump, as tcpdump currently
builds no libraries, but it's there for compatibility with libpcap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -667,6 +667,7 @@ CPPFLAGS
 ac_ct_CC
 EXEEXT
 OBJEXT
+ARCHFLAGS
 CPP
 GREP
 EGREP
@@ -1276,6 +1277,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --without-gcc           don't use gcc
+  --with-arch-flags=FLAGS Use FLAGS to specify the target architecture(s)
   --with-smi              link with libsmi (allows to load MIBs on the fly to decode SNMP packets. default=yes
   --without-smi           don't link with libsmi
   --with-user=USERNAME    drop privileges by default to USERNAME
@@ -2822,6 +2824,21 @@ ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+# Check whether --with-arch-flags was given.
+if test "${with_arch_flags+set}" = set; then
+  withval=$with_arch_flags;
+	if test "$withval" = "yes"
+	then
+	    { { echo "$as_me:$LINENO: error: No flags specified for --with-arch-flags" >&5
+echo "$as_me: error: No flags specified for --with-arch-flags" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	ARCHFLAGS="$withval"
+
+
+fi
 
 
 
@@ -14882,6 +14899,7 @@ CPPFLAGS!$CPPFLAGS$ac_delim
 ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
+ARCHFLAGS!$ARCHFLAGS$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
@@ -14902,7 +14920,7 @@ INSTALL_DATA!$INSTALL_DATA$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 71; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
